#!/usr/bin/env bash
# run-test — per-worktree isolated test gateway with dummy data.
#
# Same idea as run-test in other projects: free random 127.0.0.1 ports
# (allocated once, then stable per worktree), an isolated state dir holding
# the SQLite store + generated config, and seeded dummy conversations captured
# through the real proxy path (via scripts/mockprovider) — so nothing touches
# the main gateway's port, store, secrets, or config.
#
# Usage: bash scripts/run-test.sh [command]
#
#   run    (default) allocate ports, generate config, seed dummy data on
#          first run, then run the gateway in the foreground
#   seed   re-send the dummy conversations (gateway must be running)
#   clean  remove this worktree's state dir (.run-test/<branch>)
#
# State: .run-test/<branch>/   — env (ports + master key), gateway.toml
# (config write-back from UI mutations lands here), gateway.db (+ WAL,
# secrets, capture JSONL), bin/, mock.log, .seeded marker.
#
# The gateway serves web/index.html from the repo root, so UI edits in this
# worktree show up on browser refresh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT"

log()  { echo "[run-test] $*"; }
die()  { echo "[run-test] $*" >&2; exit 1; }

SLUG="$(git branch --show-current | tr -c 'a-z0-9-' '-' | sed 's/^-*//;s/-*$//')"
[ -n "$SLUG" ] || SLUG="worktree"
STATE="$ROOT/.run-test/$SLUG"
ENV_FILE="$STATE/env"
TOML="$STATE/gateway.toml"
SEED_MARK="$STATE/.seeded"
GATEWAY_URL=""

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

# free_port prints a free TCP port on 127.0.0.1 (bind :0, read, release).
free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

# tailscale_ipv4 prints the machine's Tailscale IPv4 (CGNAT 100.64.0.0/10),
# or nothing when tailscale is absent/down. Primary: the tailscale CLI;
# fallback: the first interface address inside the CGNAT range.
tailscale_ipv4() {
  local ip
  if command -v tailscale >/dev/null 2>&1; then
    ip="$(tailscale ip -4 2>/dev/null | head -1 || true)"
    [ -n "$ip" ] && { echo "$ip"; return 0; }
  fi
  ip -4 -o addr show scope global 2>/dev/null \
    | awk '{split($4,a,"/"); split(a[1],o,"."); if (o[1]==100 && o[2]>=64 && o[2]<=127) {print a[1]; exit}}' \
    || true
}

# port_busy reports whether something is listening on the port.
port_busy() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null || return 1
  return 0
}

# wait_up url label polls url until it answers (60 x 0.5s).
wait_up() {
  local url="$1" label="$2" i
  for i in $(seq 1 60); do
    if curl -fsS -o /dev/null "$url" 2>/dev/null; then
      log "$label is ready"
      return 0
    fi
    sleep 0.5
  done
  die "$label not ready: $url"
}

write_env_file() {
  cat > "$ENV_FILE" <<EOF
GATEWAY_PORT=$GATEWAY_PORT
MOCK_PORT=$MOCK_PORT
SHIMMER_MASTER_KEY=$SHIMMER_MASTER_KEY
TAILSCALE_IP=$TAILSCALE_IP
EOF
}

write_config() {
  # Binding policy (cmd/gateway): loopback + CGNAT (Tailscale) are allowed.
  # When a Tailscale IP exists, the gateway also listens there so the UI and
  # API are reachable from other tailnet devices. Note the /api/* surface is
  # unauthenticated: on a tailnet that means your devices only (see README
  # threat model); master-key endpoints stay loopback-only.
  local listen_addrs="'127.0.0.1:$GATEWAY_PORT'"
  if [ -n "$TAILSCALE_IP" ]; then
    listen_addrs="$listen_addrs, '$TAILSCALE_IP:$GATEWAY_PORT'"
  fi
  cat > "$TOML" <<EOF
# Generated by scripts/run-test.sh — per-worktree isolated test gateway.
# Safe to delete; regenerated on the next \`just run-test\`. UI/API config
# mutations are written back HERE, never to a real gateway.toml.
listen_addrs = [$listen_addrs]
store = '$STATE/gateway.db'
retention_days = 30

[settings]
default_alias = 'mock'
request_plugins = []
response_plugins = []
log_payloads = false

[providers.mock]
base_url = 'http://127.0.0.1:$MOCK_PORT/v1'
api_key_env = ''
models = ['test-small', 'test-large', 'test-fail']

[[instances]]
alias = 'mock'
template = 'mock'
plugins = ['sanitize_tools']
EOF
}

# ---------------------------------------------------------------------------
# setup: ports, master key, config, pricing table
# ---------------------------------------------------------------------------

mkdir -p "$STATE"

if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  . "$ENV_FILE"
fi
OLD_GW_PORT="${GATEWAY_PORT:-}"
OLD_MOCK_PORT="${MOCK_PORT:-}"
OLD_TAILSCALE_IP="${TAILSCALE_IP:-}"

# Ports are allocated once and then stable across runs (bookmarks survive).
# A busy stored port means a stale/foreign listener: refuse rather than
# silently moving (two gateways would fight over the same store).
if [ -n "${GATEWAY_PORT:-}" ] && port_busy "$GATEWAY_PORT"; then
  die "port $GATEWAY_PORT is in use — is run-test already running? Stop it first, or 'just run-test-clean'."
fi
if [ -n "${MOCK_PORT:-}" ] && port_busy "$MOCK_PORT"; then
  die "port $MOCK_PORT is in use — stop the stale process or 'just run-test-clean'."
fi
if [ -z "${GATEWAY_PORT:-}" ]; then GATEWAY_PORT="$(free_port)"; fi
if [ -z "${MOCK_PORT:-}" ]; then MOCK_PORT="$(free_port)"; fi
if [ -z "${SHIMMER_MASTER_KEY:-}" ]; then
  SHIMMER_MASTER_KEY="$(python3 -c 'import base64,os; print(base64.b64encode(os.urandom(32)).decode())')"
fi
# Re-detected every run: Tailscale IPs roam, and the config must follow.
TAILSCALE_IP="$(tailscale_ipv4)"
write_env_file

# Regenerate the config when missing or whenever the stored ports/IP moved,
# so the TOML can never point at a stale listener.
if [ ! -f "$TOML" ] || [ "$GATEWAY_PORT" != "$OLD_GW_PORT" ] || [ "$MOCK_PORT" != "$OLD_MOCK_PORT" ] || [ "$TAILSCALE_IP" != "$OLD_TAILSCALE_IP" ]; then
  write_config
  log "wrote $TOML"
fi

GATEWAY_URL="http://127.0.0.1:$GATEWAY_PORT"

# The pricing table is generated and untracked, so a fresh worktree lacks it
# (Usage would show \$0). Copy it from the main checkout when available.
if [ ! -f internal/pricing/models.json ]; then
  MAIN="$(git worktree list --porcelain | sed -n 's/^worktree //p' | head -1)"
  if [ -f "$MAIN/internal/pricing/models.json" ]; then
    mkdir -p internal/pricing
    cp "$MAIN/internal/pricing/models.json" internal/pricing/models.json
    log "copied pricing table from main checkout ($MAIN)"
  else
    log "WARN: no pricing table — Usage view will show \$0. Run 'just update-prices'."
  fi
fi

# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------

mkdir -p "$STATE/bin"
log "building gateway + mockprovider"
go build -o "$STATE/bin/mockprovider" ./scripts/mockprovider
go build -o "$STATE/bin/gateway" ./cmd/gateway

# ---------------------------------------------------------------------------
# seed: dummy conversations captured through the real proxy path
# ---------------------------------------------------------------------------

# curl without -f: HTTP error statuses are expected seed data (the "fail"
# scenario), only network failures should abort.
post_chat() { # post_chat <session-id> <body>
  curl -sS -o /dev/null -X POST "$GATEWAY_URL/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -H "X-Session-Id: $1" \
    -d "$2"
}

seed_data() {
  log "seeding dummy conversations through the gateway"
  # 1. Tool round-trip (stream:false): the tools schema carries the
  #    enum+oneOf duplication that sanitize_tools (enabled on the mock
  #    instance) rewrites — compare request vs filtered in the trace view.
  post_chat seed-weather '{"model":"mock/test-small","messages":[{"role":"user","content":"What is the weather in Berlin right now?"}],"tools":[{"type":"function","function":{"name":"get_weather","description":"Current weather for a city","parameters":{"type":"object","properties":{"location":{"type":"string","enum":["Berlin","Paris","Tokyo"],"oneOf":[{"type":"string"},{"enum":["Berlin","Paris","Tokyo"]}]},"unit":{"type":"string","enum":["celsius","fahrenheit"],"oneOf":[{"type":"string"}]}},"required":["location"]}}}]}' || die "seed: tool-call request failed"
  post_chat seed-weather '{"model":"mock/test-small","messages":[{"role":"user","content":"What is the weather in Berlin right now?"},{"role":"assistant","content":null,"tool_calls":[{"id":"call_mock_1","type":"function","function":{"name":"get_weather","arguments":"{\"location\":\"Berlin\",\"unit\":\"celsius\"}"}}]},{"role":"tool","tool_call_id":"call_mock_1","content":"{\"temp_c\":18,\"condition\":\"clear\",\"source\":\"mock\"}"}]}' || die "seed: tool-result request failed"
  # 2. Streaming multi-turn chat.
  post_chat seed-chat '{"model":"mock/test-large","stream":true,"messages":[{"role":"system","content":"You are a terse assistant."},{"role":"user","content":"Write a two-sentence haiku about capture-only gateways."}]}' || die "seed: stream request 1 failed"
  post_chat seed-chat '{"model":"mock/test-large","stream":true,"messages":[{"role":"system","content":"You are a terse assistant."},{"role":"user","content":"Write a two-sentence haiku about capture-only gateways."},{"role":"assistant","content":"Requests flow in,\nevery token quietly caught —\nthe store remembers."},{"role":"user","content":"Now make it about retention."}]}' || die "seed: stream request 2 failed"
  # 3. Upstream failure (model contains "fail" → mock returns 500).
  post_chat seed-fail '{"model":"mock/test-fail","messages":[{"role":"user","content":"Trigger the mock failure."}]}' || die "seed: failure request failed"
  # 4. Unprefixed model resolved via settings.default_alias.
  post_chat seed-default '{"model":"test-small","messages":[{"role":"user","content":"Say hi without an alias prefix."}]}' || die "seed: default-alias request failed"
  log "seeded 6 requests across 4 sessions (seed-weather, seed-chat, seed-fail, seed-default)"
}

# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

case "${1:-run}" in
  run)
    "$STATE/bin/mockprovider" -addr "127.0.0.1:$MOCK_PORT" >"$STATE/mock.log" 2>&1 &
    MOCK_PID=$!
    GW_PID=""
    cleanup() {
      [ -n "$GW_PID" ] && kill "$GW_PID" 2>/dev/null
      kill "$MOCK_PID" 2>/dev/null
      wait 2>/dev/null
    }
    trap cleanup EXIT INT TERM

    wait_up "http://127.0.0.1:$MOCK_PORT/v1/models" "mockprovider"

    SHIMMER_MASTER_KEY="$SHIMMER_MASTER_KEY" "$STATE/bin/gateway" -config "$TOML" &
    GW_PID=$!

    wait_up "$GATEWAY_URL/api/status" "gateway"

    if [ ! -f "$SEED_MARK" ]; then
      seed_data
      touch "$SEED_MARK"
    else
      log "store already seeded (delete $SEED_MARK or 'just run-test-seed' to re-seed)"
    fi

    log "UI:     $GATEWAY_URL/"
    if [ -n "$TAILSCALE_IP" ]; then
      log "Tailscale: http://$TAILSCALE_IP:$GATEWAY_PORT/  (UI + API exposed to your tailnet)"
    else
      log "(no Tailscale IP found — loopback only)"
    fi
    log "Proxy:  $GATEWAY_URL/v1  (models: mock/test-small, mock/test-large, test-small)"
    log "Store:  $STATE/gateway.db"
    log "Mock:   http://127.0.0.1:$MOCK_PORT  (log: $STATE/mock.log)"
    log "Ctrl-C to stop"
    wait "$GW_PID"
    ;;
  seed)
    if ! curl -fsS -o /dev/null "$GATEWAY_URL/api/status" 2>/dev/null; then
      die "gateway not reachable at $GATEWAY_URL — start it with 'just run-test' first"
    fi
    seed_data
    touch "$SEED_MARK"
    ;;
  clean)
    rm -rf "$STATE"
    log "removed $STATE"
    log "(if a gateway is still running from a previous run, stop it manually)"
    ;;
  *)
    die "unknown command: $1 (usage: bash scripts/run-test.sh [run|seed|clean])"
    ;;
esac
